/* ============================================================
   术语表
   ============================================================ */
window.__GLOSSARY = [
  { en: "AI", zh: "人工智能", tag: "总论", def: "让机器完成通常需要人类智能的任务（看图、说话、决策等）的技术总称。" },
  { en: "ML", zh: "机器学习", tag: "总论", def: "AI 的子集：让机器从数据中自学规律，而非人工写死规则。" },
  { en: "DL", zh: "深度学习", tag: "总论", def: "ML 中最火的一支：用多层神经网络学习，是大模型的技术基础。" },
  { en: "LLM", zh: "大语言模型", tag: "总论", def: "Large Language Model，以海量文本训练的巨型神经网络，能生成、理解和对话，如 GPT、Llama。" },
  { en: "Model", zh: "模型", tag: "总论", def: "训练完成后能对新数据做出判断/生成的“程序”，其知识存在参数里。" },
  { en: "Parameter", zh: "参数", tag: "总论", def: "神经网络里需要学习的权重和偏置，模型的知识就存在这些数字里。" },
  { en: "Supervised Learning", zh: "有监督学习", tag: "机器学习", def: "训练数据带标签（答案），模型以“纠错”方式学习。用于分类、回归。" },
  { en: "Unsupervised Learning", zh: "无监督学习", tag: "机器学习", def: "数据无标签，机器自己发现结构（聚类、降维等）。" },
  { en: "Reinforcement Learning", zh: "强化学习", tag: "机器学习", def: "让智能体在环境中试错，以奖励/惩罚学习行动策略。" },
  { en: "Feature", zh: "特征", tag: "机器学习", def: "用来描述样本的输入属性，如一张图片的像素、一条文本的向量。" },
  { en: "Label", zh: "标签", tag: "机器学习", def: "有监督学习中给样本标注的“标准答案”，如照片对应的“猫/狗”。" },
  { en: "Overfitting", zh: "过拟合", tag: "机器学习", def: "模型把训练数据背得太死，换新数据就表现差（只会套题不会迁移）。" },
  { en: "Neural Network", zh: "神经网络", tag: "神经网络", def: "由多层“神经元”组成的网络，每层做加权求和+激活，逐层提取特征。" },
  { en: "Neuron", zh: "神经元", tag: "神经网络", def: "神经网络的最小单元：输入×权重求和，加偏置，经激活函数输出。" },
  { en: "Activation Function", zh: "激活函数", tag: "神经网络", def: "给神经元加“非线性”的函数（如 ReLU），否则多层网络退化成线性的。" },
  { en: "Backpropagation", zh: "反向传播", tag: "神经网络", def: "让误差从输出层逐层传回、算出每个参数该往哪调的学习算法。" },
  { en: "Gradient Descent", zh: "梯度下降", tag: "神经网络", def: "沿着“误差下降最快的方向”逐步调整参数的优化方法。" },
  { en: "Epoch", zh: "轮次", tag: "神经网络", def: "把整个训练集完整过一遍模型算一个 epoch，通常要跑很多轮。" },
  { en: "Embedding", zh: "嵌入向量", tag: "文字表示", def: "把文字等对象转成一组数字（向量），使语义相近的对象在向量空间靠近。" },
  { en: "Vector", zh: "向量", tag: "文字表示", def: "一组有序数字，如 [0.2, -0.5, 0.8]，可表示词、句、图等。" },
  { en: "Tokenizer", zh: "分词器", tag: "文字表示", def: "把文本切成 token 的工具。" },
  { en: "Token", zh: "词元", tag: "文字表示", def: "模型处理文字的最小单位（词、词根、字或符号），计费与容量都看它。" },
  { en: "BPE", zh: "字节对编码", tag: "文字表示", def: "主流分词方法：统计高频组合并逐步合并，构造 token 词典。" },
  { en: "Attention", zh: "注意力机制", tag: "Transformer", def: "让模型处理当前词时按权重关注句子中其他相关的词。" },
  { en: "Self-Attention", zh: "自注意力", tag: "Transformer", def: "序列内部自己和自己算注意力（QKV），是 Transformer 的核心。" },
  { en: "Query / Key / Value", zh: "QKV", tag: "Transformer", def: "Q 问该关注谁、K 是各位置标签、V 是携带的内容；Q·K 比对打分后加权 V。" },
  { en: "Multi-Head Attention", zh: "多头注意力", tag: "Transformer", def: "把注意力分成多个头，每个头关注不同维度，最后拼接。" },
  { en: "Positional Encoding", zh: "位置编码", tag: "Transformer", def: "给每个 token 补上位置信息，让模型知道先后顺序。" },
  { en: "Transformer", zh: "Transformer 架构", tag: "Transformer", def: "2017 年提出的架构，靠“注意力机制”处理序列，GPT/BERT/Llama 的地基。" },
  { en: "Encoder", zh: "编码器", tag: "Transformer", def: "Transformer 中把输入序列“读进去”并转成表示的模块（如 BERT 用）。" },
  { en: "Decoder", zh: "解码器", tag: "Transformer", def: "Transformer 中逐 token 生成输出的模块（如 GPT 用，只能看左边）。" },
  { en: "Pretraining", zh: "预训练", tag: "训练", def: "用海量文本做“预测下一个词”，让模型吸收知识与语言规律。" },
  { en: "Fine-tuning", zh: "微调", tag: "训练", def: "在预训练模型之上，用特定数据再训练，让它适配某个任务/领域。" },
  { en: "SFT", zh: "监督微调", tag: "训练", def: "Supervised Fine-tuning，用人写的“问题-答案”样本教模型对话。" },
  { en: "RLHF", zh: "基于人类反馈的强化学习", tag: "训练", def: "用人类偏好排序训练奖励模型，再强化学习调优，使回答更合人类预期。" },
  { en: "Alignment", zh: "对齐", tag: "训练", def: "让模型行为符合人类意图与价值观的过程（主要靠 RLHF）。" },
  { en: "Inference", zh: "推理（预测）", tag: "训练", def: "训练完成后，用模型对新的输入做预测/生成的过程。" },
  { en: "Context Window", zh: "上下文窗口", tag: "训练", def: "模型一次能同时“看到”的 token 上限；超出部分不可见。" },
  { en: "Hallucination", zh: "幻觉", tag: "训练", def: "模型一本正经地生成不实/捏造的内容，常因知识缺失或过度自信。" },
  { en: "Prompt", zh: "提示词", tag: "应用", def: "输入给模型的话。写好 Prompt 是“提词工程”。" },
  { en: "Prompt Engineering", zh: "提示词工程", tag: "应用", def: "研究如何组织提示词以获得更好答案的技能。" },
  { en: "Chain-of-Thought", zh: "思维链", tag: "应用", def: "引导模型“先一步步思考再作答”的提示技巧，能提升推理正确率。" },
  { en: "Few-shot", zh: "少样本", tag: "应用", def: "在提示里给几个示例，让模型照此风格/结构生成。" },
  { en: "Zero-shot", zh: "零样本", tag: "应用", def: "不给示例，直接让模型完成未见过的任务。" },
  { en: "RAG", zh: "检索增强生成", tag: "应用", def: "回答前先从（向量）数据库检索相关资料拼进提示，再生成，减少幻觉。" },
  { en: "Vector Database", zh: "向量数据库", tag: "应用", def: "专门存向量并支持高效相似度检索（最近邻）的数据库，RAG 的基础设施。" },
  { en: "Agent", zh: "智能体", tag: "应用", def: "能自主拆分目标、调用工具、观察结果并迭代完成任务的 AI。" },
  { en: "Tool Use", zh: "工具调用", tag: "应用", def: "模型输出“调用某工具+参数”的指令，平台执行后回传结果，扩展能力。" },
  { en: "Multimodal", zh: "多模态", tag: "应用", def: "能同时理解/生成文字、图片、音频、视频等多种形态信息的模型。" },
  { en: "Temperature", zh: "温度参数", tag: "应用", def: "控制生成随机性的参数：越高越多样/发散，越低越稳定/保守。" },
  { en: "Top-p", zh: "核采样参数", tag: "应用", def: "只从累计概率前 p 的词里采样，控制生成多样性的另一参数。" },
  { en: "System Prompt", zh: "系统提示", tag: "应用", def: "设置模型角色与行为准则的那段底层提示，通常用户不可见。" },
  { en: "Fine-grained", zh: "细粒度", tag: "应用", def: "细节层次更细、更精确，如细粒度检索命中更准确的信息。" },
  { en: "ReAct", zh: "推理-行动范式", tag: "应用", def: "Agent 的一种经典设计：“Reason + Act”交替，先推理再行动、观察再推理。" }
];
